language: python

python:
    - "3.6"

env:
    - pip install -r requirements.txt

sudo: false

install:
    # flake8: static analysis and style checks against PEP8 
    - pip install -U flake8
    - pip install -U pytest
    - pip install -U mypy
    - pip install -U pylint

before_script:
    - flake8 .

script:
   # Static analysis
   - flake8 .
   #- pytest

matrix:
   fast_finish: true
