language: python

python:
 - "2.7"
 - "3.6"

sudo: false

install:
 - pip install pyflakes pycodestyle

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
