language: python

python:
 - "2.7"
 - "3.6"

env:
 - pip install -r requirements.txt

sudo: false

install:
 - pip install pyflakes pycodestyle
 - pip install -U pytest

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .
 - pytest

matrix:
  fast_finish: true
